### ISSUE TITLE
[suggestion] easier remote kernel usage

### ISSUE THREAD

**Issue by benneti** [dzop/emacs-jupyter#72]
What do you think of the idea to provide a simpler version of the `:session /ssh:user@remote:/run/.../jupyter/kernel-....json` with just `:session /ssh:user@remote` that starts the kernel on its own and figures out the filename.

I see that there might be an issues as it does not know the kernels on the remote from the beginning but I also feel like there should be a better way then starting the kernel on the remote and then pasting the name in the org file.

**Comment by dzop** [comment]
Yes it is possible to get the kernel information on the remote host, `jupyter-available-kernelspecs` already handles remote directories. So it would just be of modifying `org-babel-jupyter-initiate-session-by-key` to be aware of this format for `:session` and probably `jupyter-start-new-kernel` to consider remote file names.

The design of the remote kernel stuff was more focused on how to connect to an already running kernel, e.g. on some computing cluster as opposed to starting a kernel on the remote host.

**Comment by benneti** [comment]
Thanks that sounds promising, I'll have a look at it.

**Comment by benneti** [comment]
I think `jupyter-available-kernelspecs` needs a small change, too.
So what I thought of so far would that when one wants well defined behavior and different sessions on remote hosts one first needs to differentiate sessions ending with ".json" and not.
What I mean I hope can be seen in the code (that would need to distributed to the functions you talked about before) and the code is only meant to see whether this is how you would imagine it
``` emacs-lisp
;; connection file provided
(setq default-directory "/ssh:hostname:connectme.json")
;; no connection file but a named remote session
(setq default-directory "/ssh:hostname:sessionname")
;; check wether to use ssh or not
(when (string-prefix-p "/ssh:" default-directory)
  ;; check wether to use connection file
  (when (string-suffix-p ".json" default-directory)
  ;; old beviour
    )
  ;; This is the replacement necessary in jupyter-available-kernelspecs to get the kernelspec
  (let* ((host (nth 1 (split-string default-directory ":")))
         (session (nth 2 (split-string default-directory ":"))))
    (shell-command-to-string (concat "ssh " host " jupyter kernelspec list")))
  ;; then create session with necessary kernel and session id on host (org-babel-jupyter-initiate-session-by-key)
  )
```

**Comment by dzop** [comment]
About the format for the `:session` key, I think we should interpret a remote session like `/ssh:ec2:~/foo/name` as meaning start a kernel on the host `/ssh:ec2:` initially in the directory `~/foo` with the session name being `name`. This way we allow multiple sessions to be started on a remote.

Some additional rules:
- As a shorthand, `/ssh:ec2:name` will be an alias for `/ssh:ec2:~/name`.
- We should disallow `/ssh:ec2:` and `/ssh:ec2:~/foo/` since neither specify a session name.
- `/ssh:ec2:~/foo/name` and `/ssh:ec2:~/bar/name` correspond to the same session since the directory part is only used when starting the kernel. This one seems a bit fishy.

WDYT?

**Comment by benneti** [comment]
> About the format for the `:session` key, I think we should interpret a remote session like `/ssh:ec2:~/foo/name` as meaning start a kernel on the host `/ssh:ec2:` initially in the directory `~/foo` with the session name being `name`. This way we allow multiple sessions to be started on a remote.
> 
I  agree that using the file name as the session name is what looks natural.
>     * As a shorthand, `/ssh:ec2:name` will be an alias for `/ssh:ec2:~/name`.
This sounds very good
>     * We should disallow `/ssh:ec2:` and `/ssh:ec2:~/foo/` since neither specify a session name.
I agree that empty should be prohibited and a missing name, too.
>     * `/ssh:ec2:~/foo/name` and `/ssh:ec2:~/bar/name` correspond to the same session since the directory part is only used when starting the kernel. This one seems a bit fishy.
I am not sure about the folders, I don't think they are necessary and complicate things unnecessary. 
I think the easiest thing would be to only allow `/ssh:ec2:name` and then automatically choose a folder.
This seems more natural as one dosn't need to specify a folder for local kernels, too.
Then one could do something like

1. check whether the session name == host -> error no file name
```
  (let ((host (or (file-remote-p session) "local")))
    (when (string-equal session host)
      (error "No session name provided"))
      ...)
```

2. check whether there are / in the file name -> if there are, raise an error 

3. get full session path by concatenating the host with

**Comment by dzop** [comment]
Actually I think we can stick with `/ssh:ec2:name` since we can also factor in the `:dir` header argument when starting the kernel so that without a `:dir` header argument the kernel starts in the home directory of `/ssh:ec2:`, but if `:dir` is specified it starts in the directory specified by `:dir`. This is also more in-line with how `:dir` is used in regular `org-mode` blocks with sessions.

**Comment by dzop** [comment]
One issue I have found in starting a remote kernel is that there is no general way to ensure that the ports we assign to the Jupyter channels are actually available for use.

When starting a kernel on the local host, we first create a connection info file that contains all of the port numbers (among other things) that the kernel should use to bind the shell and iopub channels to. We try to guarantee that the ports the kernel binds to are actually open for use before starting the kernel by testing their availability using zmq socket connections, see `jupyter-create-connection-info`.

For a remote host, the same strategy won't work. There is no obvious way to scan the ports on the remote host to make sure that the ones we assign to the Jupyter channels are actually available.

**Comment by dangirsh** [comment]
FWIW, I'd consider it reasonable for some elisp config to be required for each remote host.

**Comment by benneti** [comment]
I think some configuration per host sounds reasonable, too. As it would still save lots of manual work if one uses the remote more than once.

As I don't know too much about networking I just assumed that the necessary ports would be forwarded by ssh with no problems and naively I assumed that the availability problem should already be adressed in `jupyter kernel` as this sets the ports up.

If there is anything I can help you with let me know.

**Comment by dzop** [comment]
Actually we can avoid the problem if we use `jupyter kernel`. We don't currently use `jupyter kernel` to start kernels, but probably should since it does take care of the availability problem. I based the whole kernel startup on https://github.com/jupyter/jupyter_client without really thinking that I already had the `jupyter kernel`  command to do all of the work.

On the local host the whole procedure for kernel startup (based on jupyter_client) is:

1. Construct a connection info plist using ports that are somewhat guaranteed to be available
2. Write the connection info plist to a file
3. Read the kernel spec JSON to construct a command for starting the kernel, passing in the connection file written in (2) as an argument
4. Start the kernel process using the command constructed in (3)

When starting a kernel on the remote host we have the extra step

5. Use the connection info plist in (1) to tunnel ports from the local host to the remote host ports of the connection info and arrange for clients to use the modified connection info plist containing the tunneled ports of the local host.

The main issue for the remote host is that there is no way of making the same guarantee about the ports in (1), but if we use `jupyter kernel` we can avoid the issue entirely since it already does all of the above steps on the remote host. Then all we would have to do is call `jupyter kernel --kernel=...` and then do (5).

**Comment by benneti** [comment]
Glad that my input was helpful.

**Comment by dzop** [comment]
I don't have a server available for testing https://github.com/dzop/emacs-jupyter/pull/102 right now, so if someone could test those changes and let me know if things are working as expected. You should just be able to specify something like
`:session /ssh:ec2:jl` and a kernel will start on the remote host `/ssh:ec2:`.

The `:dir` feature has not been added yet.

**Comment by benneti** [comment]
I think there still is a small Issue:


``` emacs-lisp
(let ((default-directory "/ssh:REMOTE:~"))
  (jupyter-available-kernelspecs)
  )
```

| python3   | /usr/share/jupyter/kernels/python3                    | :language | python | :env | nil | :display_name | Python 3    | :argv | [/usr/bin/python3 -m ipykernel -f {connection_file}]                                                                                                            |
| julia-1.0 | /home/he89baty/.local/share/jupyter/kernels/julia-1.0 | :language | julia  | :env | nil | :display_name | Julia 1.0.3 | :argv | [/home/he89baty/.local/bin/julia-1.0.3/bin/julia -i --startup-file=yes --color=yes /home/he89baty/.julia/packages/IJulia/fjEtl/src/kernel.jl {connection_file}] |
But executing 
``` org
#+begin_src jupyter-julia :session /ssh:REMOTE:jl
using Plots
#+end_src
```
results in
```

executing Jupyter-Julia code block...
Tramp: Opening connection for REMOTE using ssh...
Tramp: Sending command ‘exec ssh   -o ControlMaster=auto -o ControlPath='tramp.%C' -o ControlPersist=no -e none REMOTE’
Tramp: Waiting for prompts from remote shell...done
Tramp: Found remote shell prompt on ‘REMOTE’
Tramp: Opening connection for REMOTE using ssh...done
or: No kernel found for prefix (julia-1.1)
```
As you can see it says that on the remote no kernel `julia-1.1` is available (which is the local version I have installed).
Probably the default kernel for a language currently is chosen using the local available ones instead of per host.

Using `:kernel julia-1.0` fails, too, but with a different error namely 
```
executing Jupyter-Julia code block...
or: /ssh:fau2:/usr/bin/python3 not found in ‘exec-path’
```
This I do not get entirely, is it a problem to have the python executable in a non standard place?
As the global python version on my remote is ancient I have a more up to date local version:
```
$ ssh REMOTE which python3
~/.linuxbrew/bin/python3
```

If I should test anything else let me know and thank you for starting to implement this

**Comment by dzop** [comment]
> As you can see it says that on the remote no kernel julia-1.1 is available (which is the local version I have installed).

I fixed this in c9abe85b, but forgot to rebase the branch to include that fix.

> /ssh:fau2:/usr/bin/python3 not found in ‘exec-path’

This is because I check for the program using `executable-find` which it looks like I shouldn't do for remote hosts since I don't think `executable-find` works for those as it looks at `exec-path`.

>  is it a problem to have the python executable in a non standard place?

No, but it should be in one of the data directories found in `jupyter --paths` since we start the kernel using python directly instead of the jupyter command and we find the python that Jupyter uses by searching the data paths (and their parents) of `jupyter --paths` in the order given.

> If I should test anything else let me know

I just updated the branch, can you try again.

> thank you for starting to implement this

Its a useful feature, and I'm sure I will need it in the future so might as well implement it now :)

**Comment by benneti** [comment]
The connection is now established and it tries to start the right kernel.
But there is still a problem with the right python executable (the problem might very well be in my configuration on the remote).

The situation in more detail is:
For the remote `jupyter-locate-python` yields jupyter-locate-python `/usr/bin/python3`.
This python version fails to load the module as it is ancient.
I have a user local python version that should work available:
```
$ python3 -c "from jupyter_client.kernelapp import main; main()" --kernel=julia-1.0
[KernelApp] Starting kernel 'julia-1.0'
[KernelApp] Connection file: /run/user/30159/jupyter/kernel-63b99d58-4619-4704-bd7d-48e7ba3f12d1.json
[KernelApp] To connect a client: --existing kernel-63b99d58-4619-4704-bd7d-48e7ba3f12d1.json
```
some more details
```
$ jupyter --path
config:
    /home/USER/.config/jupyter
    /home/USER/.julia/conda/3/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/USER/.local/share/jupyter
    /home/USER/.julia/conda/3/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /run/user/30159/jupyter

$ which python3
/home/USER/.julia/conda/3/bin/python3

$ which jupyter
/home/USER/.julia/conda/3/bin/jupyter
```

As I don't completly grasp what is concatenated with what in `jupyter-locate-python` to get the executable that will be used, I basically have two questions:

1. Should the second directory in data give rise to the "right" python or are only sub directories considered (and does the last line give us the executable now)?
2. Why not use the system $PATH (as it should have the right order) to search for python?

**Comment by dzop** [comment]
> Should the second directory in data give rise to the "right" python

Yes it should. Can you replace

```emacs-lisp
(cl-loop
  for program in programs
  for spath = (expand-file-name program dir)
  thereis (setq path (and (file-exists-p spath) spath)))
```

with 

```emacs-lisp
(cl-loop
  for program in programs
  for spath = (expand-file-name program dir)
  do (message "PATH: %s" spath) and
  thereis (setq path (and (file-exists-p spath) spath)))
```

in `jupyter-locate-python` and show the output produced when you run

```emacs-lisp
(let ((default-directory "/ssh:REMOTE"))
  (jupyter-locate-python))
```

> Why not use the system $PATH

Because of the possibility that Jupyter is using a `python` not in `PATH`. When installing Jupyter, at least on my system, the paths used are all hardcoded to a specific python.

**Comment by benneti** [comment]
The output is
```
executing Elisp code block...
PATH: /ssh:REMOTE:/home/USER/.local/share/jupyter/bin/python3
PATH: /ssh:REMOTE:/home/USER/.local/share/jupyter/bin/python
PATH: /ssh:REMOTE:/home/USER/.local/share/jupyter/python3.exe
PATH: /ssh:REMOTE:/home/USER/.local/share/jupyter/python.exe
PATH: /ssh:REMOTE:/home/USER/.local/share/bin/python3
PATH: /ssh:REMOTE:/home/USER/.local/share/bin/python
PATH: /ssh:REMOTE:/home/USER/.local/share/python3.exe
PATH: /ssh:REMOTE:/home/USER/.local/share/python.exe
PATH: /ssh:REMOTE:/home/USER/.local/bin/python3
PATH: /ssh:REMOTE:/home/USER/.local/bin/python
PATH: /ssh:REMOTE:/home/USER/.local/python3.exe
PATH: /ssh:REMOTE:/home/USER/.local/python.exe
PATH: /ssh:REMOTE:/home/USER/bin/python3
PATH: /ssh:REMOTE:/home/USER/bin/python
PATH: /ssh:REMOTE:/home/USER/python3.exe
PATH: /ssh:REMOTE:/home/USER/python.exe
PATH: /ssh:REMOTE:/home/bin/python3
PATH: /ssh:REMOTE:/home/bin/python
PATH: /ssh:REMOTE:/home/python3.exe
PATH: /ssh:REMOTE:/home/python.exe
PATH: /ssh:REMOTE:/bin/python3
PATH: /ssh:REMOTE:/bin/python
PATH: /ssh:REMOTE:/python3.exe
PATH: /ssh:REMOTE:/python.exe
PATH: /ssh:REMOTE:/usr/local/share/jupyter/bin/python3
PATH: /ssh:REMOTE:/usr/local/share/jupyter/bin/python
PATH: /ssh:REMOTE:/usr/local/share/jupyter/python3.exe
PATH: /ssh:REMOTE:/usr/local/share/jupyter/python.exe
PATH: /ssh:REMOTE:/usr/local/share/bin/python3
PATH: /ssh:REMOTE:/usr/local/share/bin/python
PATH: /ssh:REMOTE:/usr/local/share/python3.exe
PATH: /ssh:REMOTE:/usr/local/share/python.exe
PATH: /ssh:REMOTE:/usr/local/bin/python3
PATH: /ssh:REMOTE:/usr/local/bin/python
PATH: /ssh:REMOTE:/usr/local/python3.exe
PATH: /ssh:REMOTE:/usr/local/python.exe
PATH: /ssh:REMOTE:/usr/bin/python3
file-remote-p: Wrong type argument: stringp, nil
```
So as it seems the `/home/USER/.julia/conda/3/share/jupyter` is not in there, as it goes to the next line first and finds a valid executable there.

**Comment by dzop** [comment]
Yes it looks like the `conda` directory is being skipped, but I don't see why that would be the case since we examine the output of `jupyter --paths` (actually `jupyter --paths --json`) which contains that directory. Can you show the output of

```(jupyter-command "--paths")```

vs

```(jupyter-command "--paths" "--json")```

where you run the commands with `default-directory` set to the remote directory.

**Comment by benneti** [comment]
That is really strange:

on the remote:
```
$ jupyter --paths
config:
    /home/USER/.config/jupyter
    /home/USER/.julia/conda/3/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/USER/.local/share/jupyter
    /home/USER/.julia/conda/3/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /run/user/30159/jupyter
 $ jupyter --paths --json
{"runtime": ["/run/user/30159/jupyter"], "config": ["/home/USER/.config/jupyter", "/home/USER/.julia/conda/3/etc/jupyter", "/usr/local/etc/jupyter", "/etc/jupyter"], "data": ["/home/USER/.local/share/jupyter", "/home/USER/.julia/conda/3/share/jupyter", "/usr/local/share/jupyter", "/usr/share/jupyter"]}
```
as you can see the folders are the same.
While when executing the corresponding funcitons in emacs yields

``` elisp
#+begin_src elisp
(let ((default-directory "/ssh:REMOTE:~"))
  (jupyter-command "--paths")
  )
#+end_src

#+RESULTS:
#+begin_example
config:
    /home/USER/.config/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/USER/.local/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /run/user/30159/jupyter
#+end_example

#+begin_src elisp
(let ((default-directory "/ssh:REMOTE:~"))
  (jupyter-command "--paths" "--json")
  )
#+end_src

#+RESULTS:
: {"runtime": ["/run/user/30159/jupyter"], "data": ["/home/USER/.local/share/jupyter", "/usr/local/share/jupyter", "/usr/share/jupyter"], "config": ["/home/USER/.config/jupyter", "/usr/local/etc/jupyter", "/etc/jupyter"]}
```

Where the right folder is missing in both cases.
As I thought that the configuration may be in a wrong place, I added it to the `~/.profile` but this does still not help.
I think the function in emacs fail to load some parts of the environment (that would be mandatory).

**Comment by benneti** [comment]
OK, I got it working by `export JUPYTER_DATA_DIR="$HOME/.julia/conda/3/share/jupyter"` in my `~/.profile`.
The problem with this is that it now only is able to use kernels in that directory as for some reason the `~./.local/share/jupyter` line is overwritten.

I think the problem is that due to the way TRAMP calls jupyter it does not set up completely and therefore the manual configuration is necessary (which I don't understand because I have no jupyter configuration in my bashrc files...).
If you have an idea to improve this please let me know (also if it is changing the remote jupyter setup).

The rest works great, connection starting the kernel, plotting.
Thank you for your work again and I think you can close the issue.

**Comment by dzop** [comment]
If you set `JUPYTER_DATA_DIR` that is what replaces the `~/.local/share/jupyter` directory. See [jupyter_core.paths.jupyter_data_dir](https://github.com/jupyter/jupyter_core/blob/51185b86423a370e62455211fe051fc569472513/jupyter_core/paths.py#L58).

It is weird that the `~/.julia/conda/3/share/jupyter` path doesn't appear because according to [jupyter_core.paths.jupyter_path](https://github.com/jupyter/jupyter_core/blob/0fe5994c2ec528de4cb01178a296d95db945fa06/jupyter_core/paths.py#L150-L155)  it should be right after `~/.local/share/jupyter`, assuming `~/.julia/conda/3` is `sys.prefix`. For it to be there it doesn't depend on any environment variables, it only depends on [this](https://github.com/jupyter/jupyter_core/blob/0fe5994c2ec528de4cb01178a296d95db945fa06/jupyter_core/paths.py#L125) line. Maybe the Jupyter script is somehow using the environment python?

**Comment by benneti** [comment]
Yes indeed it is the problem you describe, as it seems, the `PATH` I set in `.profile` is ignored, while when I set `JUPYTER_DATA_DIR` it works.

This is the relevant part of the `.profile`
```
JUPYTER_DATA_DIR="$HOME/.julia/conda/3/share/jupyter"
export JUPYTER_DATA_DIR
PATH=$HOME/.julia/conda/3/bin:$PATH
export PATH
```
If I understand the documentation right, the value for `tramp-remote-path` should be `(tramp-own-remote-path tramp-default-remote-path "/bin" ...)` but as it seems it does not work.
(`(jupyter-command "--version")` yields 4.2.1 instead of 4.4.0).

Thanks for all your help

**Comment by arthurcgusmao** [comment]
For me, it was not enough to set `JUPYTER_DATA_DIR` alone. I had to also set `JUPYTER_PATH`; without it, I was running into "`jupyter-kernel-info: Kernel did not respond to kernel-info request`". To recap my whole process:

1. Adding `tramp-own-remote-path` to `tramp-remote-path` list resolves Jupyter executable not found (if its path happens to be in the remote's path):
```lisp
(add-to-list 'tramp-remote-path 'tramp-own-remote-path)
```

2. Setting `JUPYTER_DATA_DIR` resolved `ImportError: No module named jupyter_client.kernelapp`:
```
JUPYTER_DATA_DIR="$HOME/your-miniconda3-path/share/jupyter"
export JUPYTER_DATA_DIR
```

3. Setting `JUPYTER_PATH` resolved `jupyter-kernel-info: Kernel did not respond to kernel-info request`:
```
JUPYTER_PATH="$HOME/your-miniconda3-path/share/jupyter/"
export JUPYTER_PATH
```
